/**
 * Catálogo de empresas del sector energético colombiano para el registro.
 *
 * Se construye de DOS fuentes, y el orden importa:
 *
 * 1. **Agentes con ranking de tarifas** (`hasRanking: true`) — salen de
 *    `energy.comp_ranking_market_monthly` en bia-gold. Su `id` ES el `provider`
 *    de esa matview, que es su llave primaria real; por eso resaltar la fila de
 *    quien se registra funciona sin ningún mapeo intermedio.
 * 2. **El resto del sector** (`hasRanking: false`) — del `ListadoAgentes` de XM
 *    (fuente oficial, filtrado a `State=OPERACION`). Cubre generadores,
 *    transportadores y comercializadores sin tarifa publicada. Su `id` es el
 *    código SIC.
 *
 * Por qué NO se mapea XM → gold: los nombres no coinciden y no hay puente
 * confiable. `AFINIA` en el ranking es `CARIBEMAR DE LA COSTA S.A.S. E.S.P.` en
 * XM (nombre comercial vs. razón social); `QIENERGY` es `QI ENERGY`. Un
 * matcheo automático resuelve solo 14 de 44, y adivinar el resto le asignaría a
 * un usuario la empresa equivocada. El propio DDL de gold reconoce la deuda:
 * "its provider name does not match the canonical comer list — revisit when
 * there is a stable mapping".
 *
 * El usuario SIEMPRE ve el nombre común (`name`), nunca un código ni la razón
 * social con sufijos societarios.
 *
 * Generado 2026-08-10. Regenerar cuando cambie el universo de agentes.
 */

export type ActividadEmpresa =
  | "COMERCIALIZACION"
  | "GENERACION"
  | "DISTRIBUCION"
  | "TRANSPORTE"
  | "CENTRO_RECOLECCION";

export interface EmpresaOption {
  /** Identificador estable: el `provider` de gold si tiene ranking, si no el código SIC. */
  id: string;
  /** Nombre común — lo único que ve el usuario. */
  name: string;
  /** Código SIC de XM. `null` en agentes que solo existen en gold. */
  sic: string | null;
  /** `provider` de gold. `null` si no tiene tarifa publicada. */
  goldProvider: string | null;
  activity: ActividadEmpresa;
  /** Si es true, el ranking de competitividad puede resaltar su fila. */
  hasRanking: boolean;
}

/** Sentinel para "mi empresa no está". No colisiona con ningún id real. */
export const EMPRESA_NO_LISTADA = "__OTRA__";

export const EMPRESAS: readonly EmpresaOption[] = [
  {
    id: "AFINIA",
    name: "AFINIA",
    sic: null,
    goldProvider: "AFINIA",
    activity: "DISTRIBUCION",
    hasRanking: true,
  },
  {
    id: "AIRE",
    name: "AIRE",
    sic: null,
    goldProvider: "AIRE",
    activity: "DISTRIBUCION",
    hasRanking: true,
  },
  {
    id: "BIA ENERGY",
    name: "BIA ENERGY",
    sic: null,
    goldProvider: "BIA ENERGY",
    activity: "COMERCIALIZACION",
    hasRanking: true,
  },
  {
    id: "CEDENAR",
    name: "CEDENAR",
    sic: null,
    goldProvider: "CEDENAR",
    activity: "DISTRIBUCION",
    hasRanking: true,
  },
  {
    id: "CELSIA TOLIMA",
    name: "CELSIA TOLIMA",
    sic: null,
    goldProvider: "CELSIA TOLIMA",
    activity: "DISTRIBUCION",
    hasRanking: true,
  },
  {
    id: "CELSIA VALLE",
    name: "CELSIA VALLE",
    sic: null,
    goldProvider: "CELSIA VALLE",
    activity: "DISTRIBUCION",
    hasRanking: true,
  },
  {
    id: "CENS",
    name: "CENS",
    sic: null,
    goldProvider: "CENS",
    activity: "DISTRIBUCION",
    hasRanking: true,
  },
  {
    id: "CEO",
    name: "CEO",
    sic: null,
    goldProvider: "CEO",
    activity: "DISTRIBUCION",
    hasRanking: true,
  },
  {
    id: "CETSA",
    name: "CETSA",
    sic: null,
    goldProvider: "CETSA",
    activity: "DISTRIBUCION",
    hasRanking: true,
  },
  {
    id: "CHEC",
    name: "CHEC",
    sic: null,
    goldProvider: "CHEC",
    activity: "DISTRIBUCION",
    hasRanking: true,
  },
  {
    id: "DICEL",
    name: "DICEL",
    sic: null,
    goldProvider: "DICEL",
    activity: "COMERCIALIZACION",
    hasRanking: true,
  },
  {
    id: "DICELER",
    name: "DICELER",
    sic: null,
    goldProvider: "DICELER",
    activity: "COMERCIALIZACION",
    hasRanking: true,
  },
  {
    id: "DISPAC",
    name: "DISPAC",
    sic: null,
    goldProvider: "DISPAC",
    activity: "COMERCIALIZACION",
    hasRanking: true,
  },
  {
    id: "EBSA",
    name: "EBSA",
    sic: null,
    goldProvider: "EBSA",
    activity: "DISTRIBUCION",
    hasRanking: true,
  },
  {
    id: "EDEQ",
    name: "EDEQ",
    sic: null,
    goldProvider: "EDEQ",
    activity: "DISTRIBUCION",
    hasRanking: true,
  },
  {
    id: "EEBP",
    name: "EEBP",
    sic: null,
    goldProvider: "EEBP",
    activity: "COMERCIALIZACION",
    hasRanking: true,
  },
  {
    id: "EEBPSA",
    name: "EEBPSA",
    sic: null,
    goldProvider: "EEBPSA",
    activity: "COMERCIALIZACION",
    hasRanking: true,
  },
  {
    id: "EEP",
    name: "EEP",
    sic: null,
    goldProvider: "EEP",
    activity: "DISTRIBUCION",
    hasRanking: true,
  },
  {
    id: "ELECTROCAQUETA",
    name: "ELECTROCAQUETA",
    sic: null,
    goldProvider: "ELECTROCAQUETA",
    activity: "COMERCIALIZACION",
    hasRanking: true,
  },
  {
    id: "ELECTROHUILA",
    name: "ELECTROHUILA",
    sic: null,
    goldProvider: "ELECTROHUILA",
    activity: "DISTRIBUCION",
    hasRanking: true,
  },
  {
    id: "EMCALI",
    name: "EMCALI",
    sic: null,
    goldProvider: "EMCALI",
    activity: "DISTRIBUCION",
    hasRanking: true,
  },
  {
    id: "EMSA",
    name: "EMSA",
    sic: null,
    goldProvider: "EMSA",
    activity: "DISTRIBUCION",
    hasRanking: true,
  },
  {
    id: "ENEL",
    name: "ENEL",
    sic: null,
    goldProvider: "ENEL",
    activity: "DISTRIBUCION",
    hasRanking: true,
  },
  {
    id: "ENELAR",
    name: "ENELAR",
    sic: null,
    goldProvider: "ENELAR",
    activity: "COMERCIALIZACION",
    hasRanking: true,
  },
  {
    id: "ENEL X",
    name: "ENEL X",
    sic: null,
    goldProvider: "ENEL X",
    activity: "COMERCIALIZACION",
    hasRanking: true,
  },
  {
    id: "ENERBIT",
    name: "ENERBIT",
    sic: null,
    goldProvider: "ENERBIT",
    activity: "COMERCIALIZACION",
    hasRanking: true,
  },
  {
    id: "ENERCA",
    name: "ENERCA",
    sic: null,
    goldProvider: "ENERCA",
    activity: "DISTRIBUCION",
    hasRanking: true,
  },
  {
    id: "ENERCO",
    name: "ENERCO",
    sic: null,
    goldProvider: "ENERCO",
    activity: "COMERCIALIZACION",
    hasRanking: true,
  },
  {
    id: "ENERMAS",
    name: "ENERMAS",
    sic: null,
    goldProvider: "ENERMAS",
    activity: "COMERCIALIZACION",
    hasRanking: true,
  },
  {
    id: "ENERTOTAL",
    name: "ENERTOTAL",
    sic: null,
    goldProvider: "ENERTOTAL",
    activity: "COMERCIALIZACION",
    hasRanking: true,
  },
  {
    id: "EPM",
    name: "EPM",
    sic: null,
    goldProvider: "EPM",
    activity: "DISTRIBUCION",
    hasRanking: true,
  },
  {
    id: "ESSA",
    name: "ESSA",
    sic: null,
    goldProvider: "ESSA",
    activity: "DISTRIBUCION",
    hasRanking: true,
  },
  {
    id: "NEU",
    name: "NEU",
    sic: null,
    goldProvider: "NEU",
    activity: "COMERCIALIZACION",
    hasRanking: true,
  },
  {
    id: "PEESA",
    name: "PEESA",
    sic: null,
    goldProvider: "PEESA",
    activity: "COMERCIALIZACION",
    hasRanking: true,
  },
  {
    id: "QIENERGY",
    name: "QIENERGY",
    sic: null,
    goldProvider: "QIENERGY",
    activity: "COMERCIALIZACION",
    hasRanking: true,
  },
  {
    id: "RUITOQUE",
    name: "RUITOQUE",
    sic: null,
    goldProvider: "RUITOQUE",
    activity: "COMERCIALIZACION",
    hasRanking: true,
  },
  {
    id: "SPECTRUM",
    name: "SPECTRUM",
    sic: null,
    goldProvider: "SPECTRUM",
    activity: "COMERCIALIZACION",
    hasRanking: true,
  },
  {
    id: "TENERGETICAS",
    name: "TENERGETICAS",
    sic: null,
    goldProvider: "TENERGETICAS",
    activity: "COMERCIALIZACION",
    hasRanking: true,
  },
  {
    id: "VATIA",
    name: "VATIA",
    sic: null,
    goldProvider: "VATIA",
    activity: "COMERCIALIZACION",
    hasRanking: true,
  },
  {
    id: "DTEC",
    name: "2T ENERGY",
    sic: "DTEC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EGRC",
    name: "4E GROUP",
    sic: "EGRC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EGRG",
    name: "4E GROUP",
    sic: "EGRG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "ASCC",
    name: "A.S.C. INGENIERIA",
    sic: "ASCC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "XFRG",
    name: "ABO WIND RENOVABLES PROYECTO DIECISEIS",
    sic: "XFRG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "XFRC",
    name: "ABO WIND RENOVABLES PROYECTO DIECISEIS",
    sic: "XFRC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "CHVC",
    name: "AES COLOMBIA",
    sic: "CHVC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "CHVG",
    name: "AES COLOMBIA",
    sic: "CHVG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "AESC",
    name: "AGENTE EXPERTO EN SERVICIOS PÚBLICOS",
    sic: "AESC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "CSIC",
    name: "AIR- E S.A.S. E.S.P. - INTERVENIDO",
    sic: "CSIC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "CSID",
    name: "AIR- E S.A.S. E.S.P. - INTERVENIDO",
    sic: "CSID",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "CSIG",
    name: "AIR- E S.A.S. E.S.P. - INTERVENIDO",
    sic: "CSIG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "TUSC",
    name: "ALTUS ENERGY",
    sic: "TUSC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "AMRC",
    name: "AMERICANA DE ENERGIA",
    sic: "AMRC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "AMPC",
    name: "AMPERIA",
    sic: "AMPC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "APMC",
    name: "AMPERIUM ENERGY",
    sic: "APMC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "AAGG",
    name: "ATLÁNTICA COLOMBIA",
    sic: "AAGG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "AAGC",
    name: "ATLÁNTICA COLOMBIA",
    sic: "AAGC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "ABAC",
    name: "AURES BAJO",
    sic: "ABAC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "ABAG",
    name: "AURES BAJO",
    sic: "ABAG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "AXEG",
    name: "AXIA ENERGIA",
    sic: "AXEG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "BCHG",
    name: "BCCY COLOMBIA HOLDING",
    sic: "BCHG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "BCHC",
    name: "BCCY COLOMBIA HOLDING",
    sic: "BCHC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "BCCG",
    name: "BCCY CORDOBA",
    sic: "BCCG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "BCCC",
    name: "BCCY CORDOBA",
    sic: "BCCC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "BEIG",
    name: "BEAM ENERGY INNOVATION",
    sic: "BEIG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "BEIC",
    name: "BEAM ENERGY INNOVATION",
    sic: "BEIC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "BDJG",
    name: "BIOGAS COLOMBIA",
    sic: "BDJG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "BIGC",
    name: "BIOGER",
    sic: "BIGC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "BTGC",
    name: "BTG PACTUAL COMMODITIES COLOMBIA",
    sic: "BTGC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "CBYC",
    name: "CARBOENERGY",
    sic: "CBYC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "CMMC",
    name: "CARIBEMAR DE LA COSTA",
    sic: "CMMC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "CMMD",
    name: "CARIBEMAR DE LA COSTA",
    sic: "CMMD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "CERG",
    name: "CEE ENERGY",
    sic: "CERG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "CERC",
    name: "CEE ENERGY",
    sic: "CERC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EPSC",
    name: "CELSIA COLOMBIA",
    sic: "EPSC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EPSD",
    name: "CELSIA COLOMBIA",
    sic: "EPSD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "EPST",
    name: "CELSIA COLOMBIA",
    sic: "EPST",
    goldProvider: null,
    activity: "TRANSPORTE",
    hasRanking: false,
  },
  {
    id: "EPSG",
    name: "CELSIA COLOMBIA",
    sic: "EPSG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "CEMC",
    name: "CEM - COMPAÑIA ENERGETICA MULTIREGIONAL",
    sic: "CEMC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "CMXG",
    name: "CEMEX ENERGY",
    sic: "CMXG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "CMXC",
    name: "CEMEX ENERGY",
    sic: "CMXC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "CNGD",
    name: "CEN ENERGY",
    sic: "CNGD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "CHCC",
    name: "CENTRAL HIDROELECTRICA DE CALDAS S.A. E.S.P. BENEFICIO E INTERES COLECTIVO",
    sic: "CHCC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "CHCD",
    name: "CENTRAL HIDROELECTRICA DE CALDAS S.A. E.S.P. BENEFICIO E INTERES COLECTIVO",
    sic: "CHCD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "CHCT",
    name: "CENTRAL HIDROELECTRICA DE CALDAS S.A. E.S.P. BENEFICIO E INTERES COLECTIVO",
    sic: "CHCT",
    goldProvider: null,
    activity: "TRANSPORTE",
    hasRanking: false,
  },
  {
    id: "HCCG",
    name: "CENTRAL HIDROELÉCTRICA CONCORDIA",
    sic: "HCCG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "CTZG",
    name: "CENTRAL HIDROELÉCTRICA TZ II",
    sic: "CTZG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "CHZG",
    name: "CENTRAL HIDROELÉCTRICA ZEUS",
    sic: "CHZG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "CTCG",
    name: "CENTRAL TERMOCARTAGENA",
    sic: "CTCG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "CDNC",
    name: "CENTRALES ELECTRICAS DE NARIÑO",
    sic: "CDNC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "CDND",
    name: "CENTRALES ELECTRICAS DE NARIÑO",
    sic: "CDND",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "CDNG",
    name: "CENTRALES ELECTRICAS DE NARIÑO",
    sic: "CDNG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "CDIM",
    name: "CENTRALES ELECTRICAS DEL CAUCA",
    sic: "CDIM",
    goldProvider: null,
    activity: "CENTRO_RECOLECCION",
    hasRanking: false,
  },
  {
    id: "CDID",
    name: "CENTRALES ELECTRICAS DEL CAUCA S.A. E.S.P. (INTERVENIDA)",
    sic: "CDID",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "CDIG",
    name: "CENTRALES ELECTRICAS DEL CAUCA S.A. E.S.P. (INTERVENIDA)",
    sic: "CDIG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "CDIC",
    name: "CENTRALES ELECTRICAS DEL CAUCA S.A. E.S.P. (INTERVENIDA)",
    sic: "CDIC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "CNST",
    name: "CENTRALES ELECTRICAS DEL NORTE DE SANTANDER",
    sic: "CNST",
    goldProvider: null,
    activity: "TRANSPORTE",
    hasRanking: false,
  },
  {
    id: "CNSC",
    name: "CENTRALES ELECTRICAS DEL NORTE DE SANTANDER",
    sic: "CNSC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "CNSD",
    name: "CENTRALES ELECTRICAS DEL NORTE DE SANTANDER",
    sic: "CNSD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "CTEG",
    name: "COENERGIA",
    sic: "CTEG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "CTEC",
    name: "COENERGIA",
    sic: "CTEC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "CNRC",
    name: "COENERSA",
    sic: "CNRC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "COLC",
    name: "COLENERGIA",
    sic: "COLC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "CBNC",
    name: "COLOMBINA ENERGIA",
    sic: "CBNC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "COGC",
    name: "COMERCIALIZADORA 4G ENERGIA",
    sic: "COGC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "COGG",
    name: "COMERCIALIZADORA 4G ENERGIA",
    sic: "COGG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "CVLC",
    name: "COMERCIALIZADORA DE ENERGÍA VITALUZ",
    sic: "CVLC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EREC",
    name: "COMERCIALIZADORA DE ENERGÍAS RENOVABLES GREEN ENERGY",
    sic: "EREC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "CAFC",
    name: "COMERCIALIZADORA DEL CAFE",
    sic: "CAFC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "CETC",
    name: "COMPAÑIA DE ELECTRICIDAD DE TULUA",
    sic: "CETC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "CETD",
    name: "COMPAÑIA DE ELECTRICIDAD DE TULUA",
    sic: "CETD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "CETG",
    name: "COMPAÑIA DE ELECTRICIDAD DE TULUA",
    sic: "CETG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "CLIC",
    name: "COMPAÑIA DE LUZ INTELIGENTE DE COLOMBIA - CLIC",
    sic: "CLIC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "CEOG",
    name: "COMPAÑIA ENERGETICA DE OCCIDENTE",
    sic: "CEOG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "CEOC",
    name: "COMPAÑIA ENERGETICA DE OCCIDENTE",
    sic: "CEOC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "CEOD",
    name: "COMPAÑIA ENERGETICA DE OCCIDENTE",
    sic: "CEOD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "SOCC",
    name: "COMPAÑÍA ELÉCTRICA DE SOCHAGOTA",
    sic: "SOCC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "SOCG",
    name: "COMPAÑÍA ELÉCTRICA DE SOCHAGOTA",
    sic: "SOCG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "CMCD",
    name: "COMPAÑÍA ELÉCTRICA DEL MAR CARIBE",
    sic: "CMCD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "CIEG",
    name: "COMPAÑÍA INTEGRAL ENERGETICA",
    sic: "CIEG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "CIEC",
    name: "COMPAÑÍA INTEGRAL ENERGETICA",
    sic: "CIEC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "CNAD",
    name: "CONELCA",
    sic: "CNAD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "CNXT",
    name: "CONEXIÓN Y GESTIÓN DE ACTIVOS S.A.S. E.S.P. CONEXSIS",
    sic: "CNXT",
    goldProvider: null,
    activity: "TRANSPORTE",
    hasRanking: false,
  },
  {
    id: "SOEG",
    name: "COREX ENERGY",
    sic: "SOEG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "COXG",
    name: "COX ENERGY COMERCIALIZADORA",
    sic: "COXG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "COXC",
    name: "COX ENERGY COMERCIALIZADORA",
    sic: "COXC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "DMRC",
    name: "DEMAND RESPONSE",
    sic: "DMRC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "DEPC",
    name: "DEPI ENERGY",
    sic: "DEPC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "DEPG",
    name: "DEPI ENERGY",
    sic: "DEPG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "DEGD",
    name: "DESARROLLO ELECTRICO DEL RIO GUATAPURI",
    sic: "DEGD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "DEST",
    name: "DESARROLLO ELÉCTRICO SURIA",
    sic: "DEST",
    goldProvider: null,
    activity: "TRANSPORTE",
    hasRanking: false,
  },
  {
    id: "DIST",
    name: "DISTASA",
    sic: "DIST",
    goldProvider: null,
    activity: "TRANSPORTE",
    hasRanking: false,
  },
  {
    id: "DCLC",
    name: "DISTRIBUIDORA Y COMERCIALIZADORA DE ENERGIA ELECTRICA",
    sic: "DCLC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "DRUG",
    name: "DRUMMOND POWER",
    sic: "DRUG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "DRUC",
    name: "DRUMMOND POWER",
    sic: "DRUC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "DUCG",
    name: "DUCK ENERGY",
    sic: "DUCG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "DUCC",
    name: "DUCK ENERGY",
    sic: "DUCC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "ELGC",
    name: "E.L.E.C. GREEN",
    sic: "ELGC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "ECBG",
    name: "ECOARDOBELA I",
    sic: "ECBG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "ECNG",
    name: "ECOGENERATION",
    sic: "ECNG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "ECNC",
    name: "ECOGENERATION",
    sic: "ECNC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EMMC",
    name: "ECOMMERCIAL",
    sic: "EMMC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "ECTC",
    name: "ECOPETROL ENERGÍA",
    sic: "ECTC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EDNG",
    name: "EDN COLOMBIA",
    sic: "EDNG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "CPSG",
    name: "EL CAMPANO SOLAR",
    sic: "CPSG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "TADG",
    name: "EL TAMARINDO SOLAR",
    sic: "TADG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "ESSC",
    name: "ELECTRIFICADORA DE SANTANDER",
    sic: "ESSC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "ESST",
    name: "ELECTRIFICADORA DE SANTANDER",
    sic: "ESST",
    goldProvider: null,
    activity: "TRANSPORTE",
    hasRanking: false,
  },
  {
    id: "ESSD",
    name: "ELECTRIFICADORA DE SANTANDER",
    sic: "ESSD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "CQTC",
    name: "ELECTRIFICADORA DEL CAQUETA",
    sic: "CQTC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "CQTD",
    name: "ELECTRIFICADORA DEL CAQUETA",
    sic: "CQTD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "EDIC",
    name: "ELECTRIFICADORA DEL CARIBE",
    sic: "EDIC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EDCD",
    name: "ELECTRIFICADORA DEL CARIBE",
    sic: "EDCD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "HLAC",
    name: "ELECTRIFICADORA DEL HUILA",
    sic: "HLAC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "HLAG",
    name: "ELECTRIFICADORA DEL HUILA",
    sic: "HLAG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "HLAD",
    name: "ELECTRIFICADORA DEL HUILA",
    sic: "HLAD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "EMSG",
    name: "ELECTRIFICADORA DEL META",
    sic: "EMSG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "EMSC",
    name: "ELECTRIFICADORA DEL META",
    sic: "EMSC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EMSD",
    name: "ELECTRIFICADORA DEL META",
    sic: "EMSD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "EMRC",
    name: "ELECTRIFICADORA DEL MUNICIPIO DE RIOSUCIO CHOCO",
    sic: "EMRC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EANC",
    name: "EMPRESA DE ENERGIA ANDES",
    sic: "EANC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EBSC",
    name: "EMPRESA DE ENERGIA DE BOYACA",
    sic: "EBSC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EBSD",
    name: "EMPRESA DE ENERGIA DE BOYACA",
    sic: "EBSD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "EBSG",
    name: "EMPRESA DE ENERGIA DE BOYACA",
    sic: "EBSG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "EBST",
    name: "EMPRESA DE ENERGIA DE BOYACA",
    sic: "EBST",
    goldProvider: null,
    activity: "TRANSPORTE",
    hasRanking: false,
  },
  {
    id: "CASC",
    name: "EMPRESA DE ENERGIA DE CASANARE",
    sic: "CASC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "CASD",
    name: "EMPRESA DE ENERGIA DE CASANARE",
    sic: "CASD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "EEPC",
    name: "EMPRESA DE ENERGIA DE PEREIRA",
    sic: "EEPC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EEPD",
    name: "EMPRESA DE ENERGIA DE PEREIRA",
    sic: "EEPD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "EEPG",
    name: "EMPRESA DE ENERGIA DE PEREIRA",
    sic: "EEPG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "EBPD",
    name: "EMPRESA DE ENERGIA DEL BAJO PUTUMAYO",
    sic: "EBPD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "EBPC",
    name: "EMPRESA DE ENERGIA DEL BAJO PUTUMAYO",
    sic: "EBPC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EPTG",
    name: "EMPRESA DE ENERGIA DEL PUTUMAYO",
    sic: "EPTG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "EPTC",
    name: "EMPRESA DE ENERGIA DEL PUTUMAYO",
    sic: "EPTC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EPTD",
    name: "EMPRESA DE ENERGIA DEL PUTUMAYO",
    sic: "EPTD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "EDQG",
    name: "EMPRESA DE ENERGIA DEL QUINDIO",
    sic: "EDQG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "EDQC",
    name: "EMPRESA DE ENERGIA DEL QUINDIO",
    sic: "EDQC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EDQD",
    name: "EMPRESA DE ENERGIA DEL QUINDIO",
    sic: "EDQD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "EVSC",
    name: "EMPRESA DE ENERGIA DEL VALLE DE SIBUNDOY",
    sic: "EVSC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EVSD",
    name: "EMPRESA DE ENERGIA DEL VALLE DE SIBUNDOY",
    sic: "EVSD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "EGVC",
    name: "EMPRESA DE ENERGIA ELECTRICA DEL DEPARTAMENTO DEL GUAVIARE",
    sic: "EGVC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EGVD",
    name: "EMPRESA DE ENERGIA ELECTRICA DEL DEPARTAMENTO DEL GUAVIARE",
    sic: "EGVD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "ENID",
    name: "EMPRESA DE ENERGÍA DE ARAUCA",
    sic: "ENID",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "ENIC",
    name: "EMPRESA DE ENERGÍA DE ARAUCA",
    sic: "ENIC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "VICC",
    name: "EMPRESA DE ENERGÍA ELÉCTRICA DEL DEPARTAMENTO DEL VICHADA",
    sic: "VICC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "GPEC",
    name: "EMPRESA DE GENERACION Y PROMOCION DE ENERGIA DE ANTIOQUIA",
    sic: "GPEC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "GPEG",
    name: "EMPRESA DE GENERACION Y PROMOCION DE ENERGIA DE ANTIOQUIA",
    sic: "GPEG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "ESPC",
    name: "EMPRESA DE SERVICIOS PUBLICOS DE SANTANDER",
    sic: "ESPC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "ESOC",
    name: "EMPRESA DE SERVICIOS PÚBLICOS DEL OCCIDENTE COLOMBIANO",
    sic: "ESOC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "LATC",
    name: "EMPRESA DESARROLLO ENÉRGETICO NACIONAL SOCIEDAD DE ECONOMIA MIXTA",
    sic: "LATC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EDPD",
    name: "EMPRESA DISTRIBUIDORA DEL PACIFICO",
    sic: "EDPD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "EDPC",
    name: "EMPRESA DISTRIBUIDORA DEL PACIFICO",
    sic: "EDPC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EERD",
    name: "EMPRESA ELECTRICA REGIONAL",
    sic: "EERD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "EGEG",
    name: "EMPRESA GENERADORA Y COMERCIALIZADORA DE ENERGIA ELECTRICA DE COLOMBIA",
    sic: "EGEG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "MCAG",
    name: "EMPRESA MULTIPROPOSITO DE CALARCA",
    sic: "MCAG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "EMED",
    name: "EMPRESA MUNICIPAL DE ENERGIA ELECTRICA",
    sic: "EMED",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "EMEC",
    name: "EMPRESA MUNICIPAL DE ENERGIA ELECTRICA",
    sic: "EMEC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EMEG",
    name: "EMPRESA MUNICIPAL DE ENERGIA ELECTRICA",
    sic: "EMEG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "EMPC",
    name: "EMPRESA MUNICIPAL DE SERVICIOS PUBLICOS DE CARTAGENA DEL CHAIRA",
    sic: "EMPC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "ESVC",
    name: "EMPRESA SIGLO XXI",
    sic: "ESVC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EMUG",
    name: "EMPRESA URRA",
    sic: "EMUG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "EMIC",
    name: "EMPRESAS MUNICIPALES DE CALI",
    sic: "EMIC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EMID",
    name: "EMPRESAS MUNICIPALES DE CALI",
    sic: "EMID",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "EMIG",
    name: "EMPRESAS MUNICIPALES DE CALI",
    sic: "EMIG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "CTIC",
    name: "EMPRESAS MUNICIPALES DE CARTAGO",
    sic: "CTIC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "CTID",
    name: "EMPRESAS MUNICIPALES DE CARTAGO",
    sic: "CTID",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "CALG",
    name: "EMPRESAS PUBLICAS DE CALARCA",
    sic: "CALG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "EPMG",
    name: "EMPRESAS PUBLICAS DE MEDELLIN",
    sic: "EPMG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "EPMC",
    name: "EMPRESAS PUBLICAS DE MEDELLIN",
    sic: "EPMC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EPMD",
    name: "EMPRESAS PUBLICAS DE MEDELLIN",
    sic: "EPMD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "EPMT",
    name: "EMPRESAS PUBLICAS DE MEDELLIN",
    sic: "EPMT",
    goldProvider: null,
    activity: "TRANSPORTE",
    hasRanking: false,
  },
  {
    id: "ENDD",
    name: "ENEL COLOMBIA",
    sic: "ENDD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "ENDG",
    name: "ENEL COLOMBIA",
    sic: "ENDG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "ENDC",
    name: "ENEL COLOMBIA",
    sic: "ENDC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EXEC",
    name: "ENEL X COLOMBIA",
    sic: "EXEC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "ENGG",
    name: "ENERGETICA",
    sic: "ENGG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "EGTC",
    name: "ENERGETICOS",
    sic: "EGTC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "ATEM",
    name: "ENERGIA ATENEA",
    sic: "ATEM",
    goldProvider: null,
    activity: "CENTRO_RECOLECCION",
    hasRanking: false,
  },
  {
    id: "ATEC",
    name: "ENERGIA ATENEA",
    sic: "ATEC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "ATED",
    name: "ENERGIA ATENEA",
    sic: "ATED",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "ECSD",
    name: "ENERGIA DE COLOMBIA STR",
    sic: "ECSD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "ADCG",
    name: "ENERGIA DEL RIO PIEDRAS",
    sic: "ADCG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "ADCC",
    name: "ENERGIA DEL RIO PIEDRAS",
    sic: "ADCC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "ESUG",
    name: "ENERGIA DEL SUROESTE",
    sic: "ESUG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "ELIG",
    name: "ENERGIA LIMPIA Y EFICIENTE",
    sic: "ELIG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "ELIC",
    name: "ENERGIA LIMPIA Y EFICIENTE",
    sic: "ELIC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "ERCG",
    name: "ENERGIA RENOVABLE DE COLOMBIA",
    sic: "ERCG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "RQEC",
    name: "ENERGIA Y AGUA",
    sic: "RQEC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "ENOC",
    name: "ENERGIA Y ALUMBRADO DE COLOMBIA",
    sic: "ENOC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EYCG",
    name: "ENERGIA Y GAS DE COLOMBIA",
    sic: "EYCG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "EYCC",
    name: "ENERGIA Y GAS DE COLOMBIA",
    sic: "EYCC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EASC",
    name: "ENERGY ASSET",
    sic: "EASC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "ETNC",
    name: "ENERGY TRANSITIONS",
    sic: "ETNC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EEAD",
    name: "ENERGÍA ELÉCTRICA DE LA COSTA ATLÁNTICA",
    sic: "EEAD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "ENVC",
    name: "ENERVISA",
    sic: "ENVC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EVTG",
    name: "ENERVOLTIO",
    sic: "EVTG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "EXIG",
    name: "ENERXIA COLOMBIA",
    sic: "EXIG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "EXIC",
    name: "ENERXIA COLOMBIA",
    sic: "EXIC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "TMFG",
    name: "ENFRAGEN TERMOFLORES",
    sic: "TMFG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "TMVG",
    name: "ENFRAGEN TERMOVALLE S.A.S. EMPRESA DE SERVICIOS PUBLICOS",
    sic: "TMVG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "ENZT",
    name: "ENLAZA GRUPO ENERGIA BOGOTA",
    sic: "ENZT",
    goldProvider: null,
    activity: "TRANSPORTE",
    hasRanking: false,
  },
  {
    id: "EOEG",
    name: "EOLOS ENERGÍA S.A.S. E.S.P. EN LIQUIDACIÓN",
    sic: "EOEG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "EPRC",
    name: "EPRING ENERGY",
    sic: "EPRC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "ERRG",
    name: "ERCO GENERACION",
    sic: "ERRG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "ESNG",
    name: "ES INVEST COLOMBIA",
    sic: "ESNG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "ESNC",
    name: "ES INVEST COLOMBIA",
    sic: "ESNC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "SPRC",
    name: "ESPACIO PRODUCTIVO",
    sic: "SPRC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "SPRG",
    name: "ESPACIO PRODUCTIVO",
    sic: "SPRG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "FCLC",
    name: "FACTOR LUZ",
    sic: "FCLC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "FFEC",
    name: "FORCEFUL ENERGY",
    sic: "FFEC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "FARG",
    name: "FOTOVOLTAICO ARRAYANES",
    sic: "FARG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "FYRG",
    name: "FOTOVOLTAICO EL YARUMO",
    sic: "FYRG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "FTNG",
    name: "FOTOVOLTAICO TOLIMA NORTE",
    sic: "FTNG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "FREC",
    name: "FRANCA ENERGIA",
    sic: "FREC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "FERG",
    name: "FUENTES DE ENERGIAS RENOVABLES",
    sic: "FERG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "FERC",
    name: "FUENTES DE ENERGIAS RENOVABLES",
    sic: "FERC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "GADM",
    name: "GADIZ UTILITY",
    sic: "GADM",
    goldProvider: null,
    activity: "CENTRO_RECOLECCION",
    hasRanking: false,
  },
  {
    id: "GADG",
    name: "GADIZ UTILITY",
    sic: "GADG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "GAPC",
    name: "GAP ENERGY GROUP",
    sic: "GAPC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "GALG",
    name: "GENERADORA ALEJANDRIA",
    sic: "GALG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "GBUG",
    name: "GENERADORA BUENAVISTA",
    sic: "GBUG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "GCYC",
    name: "GENERADORA CANTAYÚS",
    sic: "GCYC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "GCYG",
    name: "GENERADORA CANTAYÚS",
    sic: "GCYG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "JOAG",
    name: "GENERADORA SAN JOAQUIN",
    sic: "JOAG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "TCNG",
    name: "GENERADORA TERMOCENTRO",
    sic: "TCNG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "GECC",
    name: "GENERADORA Y COMERCIALIZADORA DE ENERGIA DEL CARIBE",
    sic: "GECC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "GECG",
    name: "GENERADORA Y COMERCIALIZADORA DE ENERGIA DEL CARIBE",
    sic: "GECG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "GEEG",
    name: "GENERAMOS ENERGIA",
    sic: "GEEG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "GASC",
    name: "GENERARCO",
    sic: "GASC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "GCOC",
    name: "GENERCOL S.A.S. E.S.P. ZOMAC",
    sic: "GCOC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "GCMG",
    name: "GENERCOMERCIAL",
    sic: "GCMG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "GSAC",
    name: "GENERSA",
    sic: "GSAC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "GSAG",
    name: "GENERSA",
    sic: "GSAG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "GNSG",
    name: "GENERSOL",
    sic: "GNSG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "GSYC",
    name: "GENERSYS",
    sic: "GSYC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "HIMC",
    name: "GESTION ENERGETICA",
    sic: "HIMC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "HIMG",
    name: "GESTION ENERGETICA",
    sic: "HIMG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "GRCG",
    name: "GR POWER COLOMBIA",
    sic: "GRCG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "GRCC",
    name: "GR POWER COLOMBIA",
    sic: "GRCC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "GYPG",
    name: "GREENDIPITY",
    sic: "GYPG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "GWOC",
    name: "GREENWOOD ENERGY",
    sic: "GWOC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "GNYG",
    name: "GREENYELLOW COMERCIALIZADORA",
    sic: "GNYG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "GNYC",
    name: "GREENYELLOW COMERCIALIZADORA",
    sic: "GNYC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "EEBD",
    name: "GRUPO ENERGIA BOGOTA",
    sic: "EEBD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "EEBT",
    name: "GRUPO ENERGIA BOGOTA",
    sic: "EEBT",
    goldProvider: null,
    activity: "TRANSPORTE",
    hasRanking: false,
  },
  {
    id: "GREC",
    name: "GRUPO ENERGÉTICO",
    sic: "GREC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "HBCG",
    name: "HIDROELECTRICA BARRANCAS",
    sic: "HBCG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "HDPG",
    name: "HIDROELECTRICA DEL ALTO PORCE",
    sic: "HDPG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "HEMG",
    name: "HIDROENERGIA DE LA MONTAÑA",
    sic: "HEMG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "HDTG",
    name: "HIDROTOLIMA",
    sic: "HDTG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "HTCC",
    name: "HT INDUSTRIES COLOMBIA",
    sic: "HTCC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "HZEG",
    name: "HZ ENERGY",
    sic: "HZEG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "HZEC",
    name: "HZ ENERGY",
    sic: "HZEC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "IAEC",
    name: "IA ENERGÍA Y GESTIÓN",
    sic: "IAEC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "IACG",
    name: "IAC ENERGY",
    sic: "IACG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "ISAT",
    name: "INTERCONEXION ELECTRICA",
    sic: "ISAT",
    goldProvider: null,
    activity: "TRANSPORTE",
    hasRanking: false,
  },
  {
    id: "ITCT",
    name: "ISA INTERCOLOMBIA",
    sic: "ITCT",
    goldProvider: null,
    activity: "TRANSPORTE",
    hasRanking: false,
  },
  {
    id: "ISGC",
    name: "ISAGEN",
    sic: "ISGC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "ISGG",
    name: "ISAGEN",
    sic: "ISGG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "ITLC",
    name: "ITALCOL ENERGIA",
    sic: "ITLC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "JRDC",
    name: "JULIA - RD",
    sic: "JRDC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "KEMC",
    name: "KEM ENERGY",
    sic: "KEMC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "ORQG",
    name: "LA ORQUIDEA SOLAR",
    sic: "ORQG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "LTEC",
    name: "LATINOAMERICAN ENERGY",
    sic: "LTEC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "LMEC",
    name: "LUMINA ENERGY",
    sic: "LMEC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "MCEC",
    name: "MCI ENERGY",
    sic: "MCEC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "MERC",
    name: "MERELEC COLOMBIA",
    sic: "MERC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "LESC",
    name: "MESSER ENERGY SERVICES",
    sic: "LESC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "NESC",
    name: "NES TRADING",
    sic: "NESC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "NEUC",
    name: "NEU ENERGY",
    sic: "NEUC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "NEXG",
    name: "NEXTGY",
    sic: "NEXG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "NEXC",
    name: "NEXTGY",
    sic: "NEXC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "NTCG",
    name: "NITRO ENERGY COLOMBIA",
    sic: "NTCG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "NUEG",
    name: "NUEVAS ENERGIAS II",
    sic: "NUEG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "SHAG",
    name: "OPERADORA SHANGRI-LA",
    sic: "SHAG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "OTAC",
    name: "OTACC GENERACION",
    sic: "OTAC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "OTAG",
    name: "OTACC GENERACION",
    sic: "OTAG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "PCYG",
    name: "P.CH EL COCUYO",
    sic: "PCYG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "PSAG",
    name: "PARQUE SOLAR ANDRÓMEDA I",
    sic: "PSAG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "SOLG",
    name: "PARQUE SOLAR COLOMBIA I",
    sic: "SOLG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "PSXG",
    name: "PARQUE SOLAR COLOMBIA X",
    sic: "PSXG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "PSVG",
    name: "PARQUE SOLAR COLOMBIA XIV",
    sic: "PSVG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "PSWG",
    name: "PARQUE SOLAR FOTOVOLTAICO WIMKE",
    sic: "PSWG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "PSGG",
    name: "PARQUE SOLAR LOS GIRASOLES",
    sic: "PSGG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "PSGC",
    name: "PARQUE SOLAR LOS GIRASOLES",
    sic: "PSGC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "OROG",
    name: "PARQUE SOLAR PUERTA DE ORO",
    sic: "OROG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "PSBG",
    name: "PCH SAN BARTOLOME",
    sic: "PSBG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "PLSC",
    name: "PLUSENERGY",
    sic: "PLSC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "PWFC",
    name: "POWER FINTECH",
    sic: "PWFC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "PRIG",
    name: "PROELECTRICA",
    sic: "PRIG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "PRIC",
    name: "PROELECTRICA",
    sic: "PRIC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "PRYC",
    name: "PROENERGY",
    sic: "PRYC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "PEEC",
    name: "PROFESIONALES EN ENERGIA",
    sic: "PEEC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "PCEG",
    name: "PROMOENERCOL COMERCIALIZADORA DE ENERGÍA",
    sic: "PCEG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "PSCG",
    name: "PROYECTO SOLAR CIMITARRA",
    sic: "PSCG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "CORG",
    name: "PROYECTO SOLAR COROZO",
    sic: "CORG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "MATG",
    name: "PROYECTO SOLAR MATIMBA II",
    sic: "MATG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "PECC",
    name: "PROYECTOS ENERGETICOS DEL CAUCA",
    sic: "PECC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "PECG",
    name: "PROYECTOS ENERGETICOS DEL CAUCA",
    sic: "PECG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "RFVG",
    name: "REFOENERGY VILLANUEVA",
    sic: "RFVG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "RPEC",
    name: "RIOPAILA ENERGÍA",
    sic: "RPEC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "RPEG",
    name: "RIOPAILA ENERGÍA",
    sic: "RPEG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "RENG",
    name: "RISARALDA ENERGIA",
    sic: "RENG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "SAPT",
    name: "SAMPI JPD",
    sic: "SAPT",
    goldProvider: null,
    activity: "TRANSPORTE",
    hasRanking: false,
  },
  {
    id: "SFEG",
    name: "SANTA FE ENERGY ZOMAC",
    sic: "SFEG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "SFEC",
    name: "SANTA FE ENERGY ZOMAC",
    sic: "SFEC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "SGMC",
    name: "SIGMA2 COMERCIALIZADORA DE ENERGIA ELECTRICA",
    sic: "SGMC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "SGMG",
    name: "SIGMA2 COMERCIALIZADORA DE ENERGIA ELECTRICA",
    sic: "SGMG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "SMTC",
    name: "SMARTEN",
    sic: "SMTC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "PTTC",
    name: "SOCIEDAD DE ECONOMIA MIXTA ALUMBRADO PUBLICO DE PITALITO",
    sic: "PTTC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "SCEG",
    name: "SOL & CIELO ENERGIA",
    sic: "SCEG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "SCEC",
    name: "SOL & CIELO ENERGIA",
    sic: "SCEC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "SDCG",
    name: "SOL DE LAS CIÉNAGAS",
    sic: "SDCG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "SEJC",
    name: "SOL DEL EJE",
    sic: "SEJC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "SOVG",
    name: "SOLANO RENOVABLES",
    sic: "SOVG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "SDEG",
    name: "SOLAR EL EDÉN",
    sic: "SDEG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "MARG",
    name: "SOLAR LAS MARIAS",
    sic: "MARG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "CSMG",
    name: "SOLAR VILLAVIEJA",
    sic: "CSMG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "SOUG",
    name: "SOUL ENERGY",
    sic: "SOUG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "SOUC",
    name: "SOUL ENERGY",
    sic: "SOUC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "SOEC",
    name: "SOUTH32 ENERGY",
    sic: "SOEC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "RTAC",
    name: "SPECTRUM RENOVAVEIS",
    sic: "RTAC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "RTAG",
    name: "SPECTRUM RENOVAVEIS",
    sic: "RTAG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "SLMG",
    name: "SPK LA MATA",
    sic: "SLMG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "SLUG",
    name: "SPK LA UNIÓN",
    sic: "SLUG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "STOC",
    name: "STOCK ENERGY",
    sic: "STOC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "SNCG",
    name: "SUNCOLOMBIA GENERACIÓN",
    sic: "SNCG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "SUNG",
    name: "SUNO",
    sic: "SUNG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "SVCG",
    name: "SVC ESP SAS ZOMAC",
    sic: "SVCG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "TAMG",
    name: "TAMARINO COLOMBIA",
    sic: "TAMG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "TGEG",
    name: "TECHNOELITE GREEN ENERGY",
    sic: "TGEG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "TGEC",
    name: "TECHNOELITE GREEN ENERGY",
    sic: "TGEC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "TCBC",
    name: "TERMO CARIBE",
    sic: "TCBC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "TCBG",
    name: "TERMO CARIBE",
    sic: "TCBG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "TMMG",
    name: "TERMO MECHERO MORRO",
    sic: "TMMG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "TBSG",
    name: "TERMOBARRANQUILLA S.A. EMPRESA DE SERVICIOS PUBLICOS",
    sic: "TBSG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "TCIG",
    name: "TERMOCANDELARIA",
    sic: "TCIG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "TRIG",
    name: "TERMOCARTAGENA S.A. E.S.P. (REESTRUCTURADO)",
    sic: "TRIG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "TEMG",
    name: "TERMOEMCALI I",
    sic: "TEMG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "TMNG",
    name: "TERMONORTE",
    sic: "TMNG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "TRPC",
    name: "TERMOPIEDRAS",
    sic: "TRPC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "TRPG",
    name: "TERMOPIEDRAS",
    sic: "TRPG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "TERG",
    name: "TERMOTASAJERO DOS",
    sic: "TERG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "TRMG",
    name: "TERMOTASAJERO",
    sic: "TRMG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "TYPG",
    name: "TERMOYOPAL GENERACION",
    sic: "TYPG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "TPLC",
    name: "TERPEL ENERGÍA",
    sic: "TPLC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "TENC",
    name: "TRANSACCIONES ENERGÉTICAS S.A.S. EMPRESA DE SERVICIOS PÚBLICOS",
    sic: "TENC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "TRST",
    name: "TRANSELCA",
    sic: "TRST",
    goldProvider: null,
    activity: "TRANSPORTE",
    hasRanking: false,
  },
  {
    id: "TCET",
    name: "TRANSMISORA COLOMBIANA DE ENERGIA",
    sic: "TCET",
    goldProvider: null,
    activity: "TRANSPORTE",
    hasRanking: false,
  },
  {
    id: "TECD",
    name: "TRANSPORTADORA ELECTRICA DEL CARIBE",
    sic: "TECD",
    goldProvider: null,
    activity: "DISTRIBUCION",
    hasRanking: false,
  },
  {
    id: "TRNG",
    name: "TRINA SOLAR GENERADOR COLOMBIA - CAMPANO",
    sic: "TRNG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "TRGG",
    name: "TRINA SOLAR GENERADOR COLOMBIA - CARTAGO",
    sic: "TRGG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "TRFG",
    name: "TRINA SOLAR GENERADOR COLOMBIA - SAN FELIPE",
    sic: "TRFG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "UNGG",
    name: "UNERGY ENERGY DIGITAL",
    sic: "UNGG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "UNGC",
    name: "UNERGY ENERGY DIGITAL",
    sic: "UNGC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "VCHG",
    name: "VACHE",
    sic: "VCHG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "VNRG",
    name: "VIENTOS DEL NORTE S.A.S. E.S.P. EN LIQUIDACIÓN",
    sic: "VNRG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "VESG",
    name: "VOLTAJE EMPRESARIAL",
    sic: "VESG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "VESC",
    name: "VOLTAJE EMPRESARIAL",
    sic: "VESC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "WSLG",
    name: "WILCHES SOLAR",
    sic: "WSLG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "XTEC",
    name: "XT ENERGÍA",
    sic: "XTEC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "SPKG",
    name: "ZELESTRA COLOMBIA",
    sic: "SPKG",
    goldProvider: null,
    activity: "GENERACION",
    hasRanking: false,
  },
  {
    id: "ZONC",
    name: "ZONERGY",
    sic: "ZONC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
  {
    id: "ERNC",
    name: "ÉRGON ENERGY",
    sic: "ERNC",
    goldProvider: null,
    activity: "COMERCIALIZACION",
    hasRanking: false,
  },
] as const;

export const getEmpresaById = (id: string): EmpresaOption | undefined =>
  EMPRESAS.find((e) => e.id === id);

/**
 * Una empresa puede tener varios `EmpresaOption` — uno por actividad
 * (comercialización, distribución, generación...), cada uno con su propio SIC
 * o `provider`. Ej.: "AIR-E" tiene tres códigos SIC (CSIC/CSID/CSIG) y
 * "VOLTAJE EMPRESARIAL" tiene dos. Para el usuario es UNA empresa, así que el
 * buscador la muestra una sola vez y solo pregunta la actividad cuando hace
 * falta desambiguar.
 */
export interface EmpresaGroup {
  name: string;
  options: readonly EmpresaOption[];
  /** true si CUALQUIERA de sus actividades tiene tarifa publicada. */
  hasRanking: boolean;
}

const buildEmpresaGroups = (): readonly EmpresaGroup[] => {
  const byName = new Map<string, EmpresaOption[]>();
  for (const empresa of EMPRESAS) {
    const existing = byName.get(empresa.name);
    if (existing === undefined) byName.set(empresa.name, [empresa]);
    else existing.push(empresa);
  }
  // La clave del Map ya ES el nombre del grupo, así que no hace falta leerlo
  // de `options[0]` (que el tipo no puede garantizar que exista).
  return Array.from(byName, ([name, options]) => ({
    name,
    options,
    hasRanking: options.some((o) => o.hasRanking),
  }));
};

export const EMPRESA_GROUPS: readonly EmpresaGroup[] = buildEmpresaGroups();
